### ISSUE TITLE
Rule removing redundant trailing slashes from links

### ISSUE THREAD

**Issue by DamianGlowala** [eslint/eslint-plugin-markdown#228]
Would it be reasonable to introduce a rule which would remove redundant trailing slashes from links? This is something I did manually for the Nuxt's documentation in the [following PR](https://github.com/nuxt/nuxt/pull/23744), but there's an [open question](https://github.com/nuxt/nuxt/pull/23744#issuecomment-1768247356) whether this could be detected with a rule.

**Comment by mdjermanovic** [comment]
`eslint-plugin-markdown` doesn't provide any rules, just a [processor](https://eslint.org/docs/latest/extend/custom-processors) that extracts code blocks from markdown documents so that the code in code blocks (e.g., JavaScript) can be linted with ESLint.

If you're looking for a tool that lints markdown, check `markdownlint`:

https://github.com/DavidAnson/markdownlint
