### ISSUE TITLE
Ability to customize codeblock tags

### ISSUE THREAD

**Issue by privatenumber** [eslint/eslint-plugin-markdown#82]
Currently working with Vue and we'd like to document our examples in markdown with this plugin. However, we have been using:
```
> ```vue
> ...
> ```
```

I'd like to be able to customize the tags used for the code block.

**Comment by btmills** [comment]
I want to to support this. Unfortunately, processor plugin settings seem to be pretty difficult due to API limitations. There's a workaround in [`eslint-plugin-html`](https://github.com/BenoitZugmeyer/eslint-plugin-html):

https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/f3396817943c52d9c20c5c46e2cfca2d13353c3e/src/index.js#L11-L19

I really don't want to patch `Linter.verify`, so first I'll see if there's a way to get official support for processor plugin options in ESLint core.

**Comment by j-f1** [comment]
You could add an `eslint-plugin-markdown` key to `package.json`:

```js
{
  // ...
  "eslint-plugin-markdown": {
    "languages": [
      "ts",
      "js"
    ]
   }
}
```

**Comment by btmills** [comment]
We just merged an ESLint RFC that will will provide support for this! https://github.com/eslint/rfcs/tree/master/designs/2018-processors-improvements Once it's implemented in ESLint, we'll be able to add support into the plugin.

**Comment by henriollik** [comment]
Would also like to know about progress on this.

**Comment by seedy** [comment]
I have a specific use case for this feature.

I work on a project in which we display code examples in `.md` files via styleguidist.

The specific logic for this lib is that it ignores ```js static blocks. So I'd like to tell the same to `eslint-plugin-markdown`

So far, my workaround is to prefix each of these blocks with `<!-- eslint-skip -->`

**Comment by btmills** [comment]
:wave: I'm now actively working on implementing the new processor API so that this plugin can extract code blocks of any syntax and pass them to ESLint! I'm tracking progress in #138, so subscribe to that issue if you'd like updates, and I'll close this so that #138 is the primary issue for this work.
